Update
- 优化版本获取方式

diff --git a/.github/workflows/ci-grafana.yaml b/.github/workflows/ci-grafana.yaml
--- a/.github/workflows/ci-grafana.yaml
+++ b/.github/workflows/ci-grafana.yaml
@@ -17,11 +17,11 @@ jobs:
     permissions:
       contents: read
     outputs:
-      os_id: ${{ steps.parse.outputs.os_id }}
-      pd_id: ${{ steps.parse.outputs.pd_id }}
+      os_nme: ${{ steps.parse.outputs.os_nme }}
       os_ver: ${{ steps.parse.outputs.os_ver }}
-      go_ver: ${{ steps.parse.outputs.go_ver }}
+      pd_nme: ${{ steps.parse.outputs.pd_nme }}
       pd_ver: ${{ steps.parse.outputs.pd_ver }}
+      go_ver: ${{ steps.parse.outputs.go_ver }}
     steps:
       - name: Checkout
         uses: actions/checkout@v5
@@ -29,32 +29,36 @@ jobs:
         id: parse
         shell: bash
         run: |
-          if [ ! -f "ARGs" ]; then
+          if [ ! -f "Dockerfile" ]; then
             echo "Error: No such file or directory"
             exit 1
           fi
-          OS_ID=$(grep -E '^OS_ID=' ARGs | head -n 1 | sed 's/^OS_ID=\(.*\)/\1/' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
-          PD_ID=$(grep -E '^PD_ID=' ARGs | head -n 1 | sed 's/^PD_ID=\(.*\)/\1/' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
-          OS_VER=$(grep -E '^OS_VER=' ARGs | head -n 1 | sed 's/^OS_VER=\(.*\)/\1/' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
-          GO_VER=$(grep -E '^GO_VER=' ARGs | head -n 1 | sed 's/^GO_VER=\(.*\)/\1/' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
-          PD_VER=$(grep -E '^PD_VER=' ARGs | head -n 1 | sed 's/^PD_VER=\(.*\)/\1/' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
+          OS_NME=$(grep -E '^FROM\sgolang:' Dockerfile | head -n 1 | sed 's/^FROM\sgolang:\(.*\)-\(.*\)\sAS\(.*\)/\2/'| sed 's/[^a-zA-Z]//g' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
+          OS_VER=$(grep -E '^FROM\sgolang:' Dockerfile | head -n 1 | sed 's/^FROM\sgolang:\(.*\)-\(.*\)\sAS\(.*\)/\2/'| sed 's/[^0-9.]//g' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
+          AF_NME=$(grep -E '^WORKDIR\s/tmp/' Dockerfile | head -n 1 | awk -F '/' '{print $3}' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
+          AF_VER=$(grep -E '^ENV\sVERSION=' Dockerfile | tail -n 1 | sed 's/^ENV\sVERSION=\(.*\)/\1/' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
           # check if values are empty
-          if [ -z "$OS_ID" ] || [ -z "$PD_ID" ] || [ -z "$OS_VER" ] || [ -z "$GO_VER" ] || [ -z "$PD_VER" ]; then
+          if [ -z "$OS_NME" ] || [ -z "$OS_VER" ] || [ -z "$AF_NME" ] || [ -z "$AF_VER" ]; then
+            echo "Error: One or more ARG values are empty"
+            exit 1
+          fi
+          GO_VER=$(grep -E '^FROM\sgolang:' Dockerfile | head -n 1 |  sed 's/^FROM\sgolang:\(.*\)-\(.*\)AS\(.*\)/\1/' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
+          ND_VER=$(grep -E '^FROM\snode:' Dockerfile | head -n 1 |  sed 's/^FROM\snode:\(.*\)-\(.*\)AS\(.*\)/\1/' | sed 's/^[[:space:]"]*//;s/[[:space:]"]*$//')
+          if [ -z "$GO_VER" ] || [ -z "$ND_VER" ]; then
             echo "Error: One or more ARG values are empty"
             exit 1
           fi
           # echo results
-          echo "OS_ID='${OS_ID}'"
-          echo "PD_ID='${PD_ID}'"
-          echo "OS_VER='${OS_VER}'"
-          echo "GO_VER='${GO_VER}'"
-          echo "PD_VER='${PD_VER}'"
+          echo "Base OS: '${OS_NME}'-'${OS_VER}'"
+          echo "Artifacts: '${AF_NME}'-'${AF_VER}'"
+          echo "golang: '${GO_VER}'"
+          echo "nodejs: '${ND_VER}'"
           # set outputs
-          echo "os_id=${OS_ID}" >> $GITHUB_OUTPUT
-          echo "pd_id=${PD_ID}" >> $GITHUB_OUTPUT
+          echo "os_nme=${OS_NME}" >> $GITHUB_OUTPUT
           echo "os_ver=${OS_VER}" >> $GITHUB_OUTPUT
+          echo "pd_nme=${AF_NME}" >> $GITHUB_OUTPUT
+          echo "pd_ver=${AF_VER}" >> $GITHUB_OUTPUT
           echo "go_ver=${GO_VER}" >> $GITHUB_OUTPUT
-          echo "pd_ver=${PD_VER}" >> $GITHUB_OUTPUT
   build:
     name: Build and Push (${{ matrix.arch }})
     permissions:
@@ -90,7 +94,7 @@ jobs:
         uses: docker/build-push-action@v6
         with:
           push: true
-          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ needs.prepare.outputs.pd_id }}:${{ steps.normalize.outputs.arch_tag }}
+          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ needs.prepare.outputs.pd_nme }}:${{ steps.normalize.outputs.arch_tag }}
   merge:
     name: Create and Push Multi-Arch Manifest
     runs-on: ubuntu-24.04
@@ -109,9 +113,9 @@ jobs:
       - name: Create and Push Manifest linux/amd64, linux/arm64
         run: |
           docker buildx imagetools create \
-            --tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ needs.prepare.outputs.pd_id }}:${{ needs.prepare.outputs.pd_ver }}-${{ env.BASE_IMAGE }}${{ needs.prepare.outputs.os_ver }} \
-            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ needs.prepare.outputs.pd_id }}:amd64 \
-            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ needs.prepare.outputs.pd_id }}:arm64
+            --tag ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ needs.prepare.outputs.pd_nme }}:${{ needs.prepare.outputs.pd_ver }}-${{ env.BASE_IMAGE }}${{ needs.prepare.outputs.os_ver }} \
+            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ needs.prepare.outputs.pd_nme }}:amd64 \
+            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ needs.prepare.outputs.pd_nme }}:arm64
   cleanup:
     name: Cleanup Obsoleting Tags
     runs-on: ubuntu-slim
@@ -127,7 +131,7 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           OWNER=${{ github.repository_owner }}
-          IMAGE=${{ needs.prepare.outputs.pd_id }}
+          IMAGE=${{ needs.prepare.outputs.pd_nme }}
           for TAG in amd64 arm64; do
             VERSION_ID=$(gh api -H "Accept: application/vnd.github+json" \
               /users/$OWNER/packages/container/$IMAGE/versions \
@@ -146,4 +150,4 @@ jobs:
           delete-untagged: true
           owner: ${{ github.repository_owner }}
           token: ${{ secrets.GITHUB_TOKEN }}
-          package: ${{ needs.prepare.outputs.pd_id }}
+          package: ${{ needs.prepare.outputs.pd_nme }}
